#Build NodeJS Express App using Azure Pipelines

pool:
    vmImage: 'Ubuntu 16.04'

steps:
- task: nodeTool@0
    inputs:
    versionSpec: '8.x'
    displayName: "Node Tool"

- script:
    npm install
    npm test
    displayName: "NPM install test"

-task: PublishTestResults@2
inputs: 
    testReultsFiles: '**/TEST-RESULT.xml'
    testRunTitle: 'Test results for Javascript'

- task: PublishCodeCoverageResults@1
    inputs: 
        codeCoverageTool: Cobertura
        summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/*coverage.xml'
        reportDirectory: '$/System.DefaultWorkingDirectory)/**/coverage'

- task: ArchiveFile@2
    inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
        includeRootFolder:false

- task: PubsishBuildArtifacts@1